#!/bin/bash
# lab10; Can Shi; 040806036; 322; mycalc; Jan 03, 2018; this program performs addition and subtraction.


clear

function add ( )
{
	(( result =  $1 + $2 ))
	echo "The sum of $1 plus $2 equals $result " 
}

function subtract ( )
{
	(( result = $1 - $2 ))
	echo "The difference of $1 subtract $2 equals $result "
}

if [ "$#" = 3  ]
then
	if [ "$2" = "+" ] 
	then
		add $1 $3
	elif [ "$2" = "-" ]
	then
		subtract $1 $3
	else
		echo "Invalid input, this program can only do addition and subtraction"
	fi

elif [ "$#" = 0 ] 
then
	choice=n
	while [ "$choice" != "X" ] && [ "$choice" != "x" ];
	do
	echo "C) Calculation"
	echo "X) Exit"
	echo
	read -p "Please choose an option: " choice
	if [ "$choice" = "C" ] || [ "$choice" = "c" ]
	then
		choice1=n
		while [ "$choice1" != "X" ] && [ "$choice1" != "x" ]
		do
		read -p "Please enter an integer number or X to exit: " choice1
			 if [ "$choice1" = "X" ] || [ "$choice1" = "x" ]
                         then
                             exit 0
			elif [ "$choice1" -eq "$choice1" ]
			then
				choice2=n
				while [ "$choice2" != "X" ] && [ "$choice2" != "x" ]
				do
					echo "+) Add"
					echo "-) Subtract"
					echo "X) Exit"
					read -p "Please choose an option: " choice2
					if [ "$choice2" = "X" ] || [ "$choice2" = "x" ]
                                        then
                                                exit 0
					elif [ "$choice2" = "+" ] || [ "$choice2" = "-" ]
					then
					choice3=n
					while [ "$choice3" != "X" ] && [ "$choice3" != "x" ]
					do
					read -p "Please enter an integer number or X to exit: " choice3
					if [ "$choice3" = "X" ] || [ "$choice3" = "x" ]
					then
						exit 0

					elif [ "$choice3" -eq "$choice3" ]
                        		then 
						if [ "$choice2" = "+" ]
						then
							add $choice1 $choice3
							sleep 3
							exec $0
						elif [ "$choice2" = "-" ]
						then
							subtract $choice1 $choice3	
							sleep 3
							exec $0
						else
							echo
						fi			
					
					else
					echo
					fi
					done
				else
				echo
				fi
				done	
			else
			echo
			fi
			done
	else 
	echo
	fi
	sleep 3
	done

else 
	echo "invalid input"
fi

 
